- name: Create ansible user
  user:
    name: ansible
    uid: 900

- name: Create ansible cronjob
  cron:
    user: ansible
    name: "ansible provisioning"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/micahhouse/ansible-scripts.git > /dev/null"

- name: Copy ansible sudoers file
  copy:
    src: files/ansible_sudoers
    dest: /etc/sudoers.d/ansible

- name: Create 9:30pm shutdown cronjob
  cron:
    user: ansible
    name: "nightly reboot"
    minute: "30"
    hour: "21"
    job: "/sbin/shutdown -h 0 > /dev/null"

- name: Create 9:00pm update cronjob
  cron:
    user: ansible
    name: "nightly reboot"
    minute: "0"
    hour: "21"
    job: "/usr/bin/ansible-pull -U https://github.com/micahhouse/ansible-scripts.git tasks/nightly.yml > /dev/null"
