- name: Create Managed Policy Folder
  file:
    path: /etc/opt/chrome/managed
    state: directory
    owner: root
    group: root
    mode: 0700
    recurse: yes
 
- name: Create Reccomended Policy Folder
  file:
    path: /etc/opt/chrome/reccomended
    state: directory
    owner: root
    group: root
    mode: 0700
    recurse: yes

- name: Copy Managed Policy
  copy:
    src: files/managed_policies.json
    dest: /etc/opt/chrome/managed
    owner: root
    group: root
    mode: 0700
    
- name: Copy Reccomended Policy
  copy:
    src: files/reccomended_policies.json
    dest: /etc/opt/chrome/reccomended
    owner: root
    group: root
    mode: 0700
