- name: Enable Guest User 1
  lineinfile:
    path: /usr/share/lightdm/lightdm.conf.d/50-disable-guest.conf
    line: '{{item}}'
  with_items:
    - 'allow-guest=true'
    - 'autologin-guest=true'
    - 'autologin-session=lightdm-autologin'
    - 'autologin-user-timeout=0'
    
- name: Enable Guest User 2
  line: 'allow-guest=false'
    state: absent
