- name: Update package lists
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade System
  apt:
    upgrade: dist

- name: Create ansible user
  user:
    name: ansible
    uid: 900

- name: Create ansible cronjob
  cron:
    user: ansible
    name: "ansible provisioning"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/foundationkitty/afterschool-ansible.git > /dev/null"

- name: Copy ansible sudoers file
  copy:
    src: files/ansible_sudoers
    dest: /etc/sudoers.d/ansible
