- name: Upgrade System
  include_tasks: tasks/upgrade.yml
  
- name: Enable Guest Account
  lineinfile:
    path: /usr/share/lightdm/lightdm.conf.d/50-disable-guest.conf
    regexp: 'allow-guest=false'
    line: 'allow-guest=true'

- name: Create ansible user
  user:
    name: ansible
    uid: 900

- name: Create ansible cronjob
  cron:
    user: ansible
    name: "ansible provisioning"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/micahhouse/ansible-scripts.git > /dev/null"

- name: Copy ansible sudoers file
  copy:
    src: files/ansible_sudoers
    dest: /etc/sudoers.d/ansible

- name: Copy Wallpaper
  copy:
    src: files/.wp.jpg
    dest: /home/micah/Pictures

- name: Chmod Wallpaper
  file:
    path: /home/micah/Pictures/.wp.jpg
    mode: 0755

- name: Chmod Wallpaper Script
  file:
    path: files/wallpaper.sh
    mode: 0755

- name: Set Wallpaper
  shell: files/wallpaper.sh
