- name: Install Ansible Automation
  include_tasks: tasks/ansible.yml

- name: Enable Guest User
  include_tasks: tasks/guest.yml

- name: Add Repos
  include_tasks: tasks/repos.yml

- name: Upgrade System
  include_tasks: tasks/upgrade.yml
  
- name: Install Packages
  include_tasks: tasks/packages.yml
