- name: Install Ansible Automation
  include_tasks: tasks/ansible.yml

- name: Enable Guest User
  include_tasks: tasks/guest.yml

- name: Add Repos
  include_tasks: tasks/repos.yml

- name: Upgrade System
  include_tasks: tasks/upgrade.yml
  
- name: Install Packages
  include_tasks: tasks/packages.yml

- name: Import Chrome Policies
  include_tasks: tasks/chrome.yml
 
- name: Enable UFW
  include_tasks: tasks/ufw.yml

- name: Extract skel
  include_tasks: tasks/skel.yml

- name: Make Boot Silent
  include_tasks: tasks/silent.yml
