- hosts: localhost
  become: true
  tasks:

  - name: Update package lists
    apt:
      update_cache: yes

  - name: Upgrade System
    apt:
      upgrade: dist
    
  - name: Autoclean
    apt:
      autoclean: yes

  - name: Autoremove
    apt:
      autoremove: yes
