- name: Add Google Chrome Signing Key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub

- name: Add Google Chrome Repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

- name: Update package lists
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade System
  apt:
    upgrade: dist
    
- name:
  apt:
    name:
    - google-chrome-stable
